// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tree.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Usage int32

const (
	Usage_CREATE   Usage = 0
	Usage_ADD      Usage = 1
	Usage_FIND     Usage = 2
	Usage_REMOVE   Usage = 3
	Usage_TRAVERSE Usage = 4
	Usage_DELETE   Usage = 5
)

var Usage_name = map[int32]string{
	0: "CREATE",
	1: "ADD",
	2: "FIND",
	3: "REMOVE",
	4: "TRAVERSE",
	5: "DELETE",
}

var Usage_value = map[string]int32{
	"CREATE":   0,
	"ADD":      1,
	"FIND":     2,
	"REMOVE":   3,
	"TRAVERSE": 4,
	"DELETE":   5,
}

func (x Usage) String() string {
	return proto.EnumName(Usage_name, int32(x))
}

func (Usage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{0}
}

type Request struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Type                 Usage    `protobuf:"varint,3,opt,name=type,proto3,enum=messages.Usage" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Request) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetType() Usage {
	if m != nil {
		return m.Type
	}
	return Usage_CREATE
}

type Response struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Response) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Traverse struct {
	Values               []*Response `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Traverse) Reset()         { *m = Traverse{} }
func (m *Traverse) String() string { return proto.CompactTextString(m) }
func (*Traverse) ProtoMessage()    {}
func (*Traverse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{2}
}

func (m *Traverse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Traverse.Unmarshal(m, b)
}
func (m *Traverse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Traverse.Marshal(b, m, deterministic)
}
func (m *Traverse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Traverse.Merge(m, src)
}
func (m *Traverse) XXX_Size() int {
	return xxx_messageInfo_Traverse.Size(m)
}
func (m *Traverse) XXX_DiscardUnknown() {
	xxx_messageInfo_Traverse.DiscardUnknown(m)
}

var xxx_messageInfo_Traverse proto.InternalMessageInfo

func (m *Traverse) GetValues() []*Response {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("messages.Usage", Usage_name, Usage_value)
	proto.RegisterType((*Request)(nil), "messages.Request")
	proto.RegisterType((*Response)(nil), "messages.Response")
	proto.RegisterType((*Traverse)(nil), "messages.Traverse")
}

func init() { proto.RegisterFile("tree.proto", fileDescriptor_cb3889276909882a) }

var fileDescriptor_cb3889276909882a = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xdd, 0xa4, 0x49, 0xb7, 0xa3, 0xd4, 0x65, 0xf0, 0x90, 0x63, 0x88, 0x97, 0xd0, 0x43,
	0x0e, 0x11, 0xbc, 0x07, 0xb3, 0x82, 0x50, 0x15, 0xc6, 0xb5, 0xf7, 0x48, 0x07, 0x29, 0xd5, 0x26,
	0x66, 0xb7, 0x85, 0xfe, 0x7b, 0xd9, 0xad, 0xc5, 0xd3, 0xee, 0x9b, 0x37, 0x7c, 0x1f, 0x0c, 0x80,
	0x1b, 0x99, 0xab, 0x61, 0xec, 0x5d, 0x8f, 0xf2, 0x9b, 0xad, 0xed, 0x3e, 0xd9, 0x16, 0x06, 0xa6,
	0xc4, 0x3f, 0x7b, 0xb6, 0x0e, 0x6f, 0x20, 0x71, 0xfd, 0x96, 0x77, 0x99, 0xc8, 0x45, 0x39, 0xa3,
	0x53, 0xc0, 0x39, 0x44, 0x9b, 0x75, 0x16, 0xe5, 0xa2, 0x4c, 0x28, 0xda, 0xac, 0xf1, 0x16, 0x26,
	0xee, 0x38, 0x70, 0x16, 0xe7, 0xa2, 0x9c, 0xd7, 0xd7, 0xd5, 0x99, 0x54, 0xbd, 0xfb, 0x87, 0x42,
	0x59, 0xd4, 0x20, 0x89, 0xed, 0xd0, 0xef, 0x2c, 0xa3, 0x82, 0x78, 0xcb, 0xc7, 0x00, 0x4d, 0xc8,
	0x7f, 0xbd, 0xe8, 0xd0, 0x7d, 0xed, 0x39, 0x50, 0x67, 0x74, 0x0a, 0xc5, 0x3d, 0x48, 0x33, 0x76,
	0x07, 0x1e, 0x2d, 0xe3, 0x02, 0xd2, 0x30, 0xb4, 0x99, 0xc8, 0xe3, 0xf2, 0xb2, 0xc6, 0x7f, 0xcd,
	0x99, 0x4b, 0x7f, 0x1b, 0x8b, 0x25, 0x24, 0x41, 0x8d, 0x00, 0xe9, 0x03, 0xe9, 0xc6, 0x68, 0x75,
	0x81, 0x53, 0x88, 0x9b, 0xb6, 0x55, 0x02, 0x25, 0x4c, 0x1e, 0x9f, 0x5e, 0x5a, 0x15, 0xf9, 0x9a,
	0xf4, 0xf3, 0xeb, 0x4a, 0xab, 0x18, 0xaf, 0x40, 0x1a, 0x6a, 0x56, 0x9a, 0xde, 0xb4, 0x9a, 0xf8,
	0xa6, 0xd5, 0x4b, 0x6d, 0xb4, 0x4a, 0x3e, 0xd2, 0x70, 0xa0, 0xbb, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x5d, 0x4a, 0x62, 0xfc, 0x2e, 0x01, 0x00, 0x00,
}
